include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_specify_types: true
    prefer_const_constructors: true
    avoid_print: true
    avoid_unnecessary_containers: true
    require_trailing_commas: true
    avoid_empty_else: true
    prefer_const_literals_to_create_immutables: true
    no_logic_in_create_state: true
    annotate_overrides: true
    prefer_is_empty: true
    prefer_is_not_empty: true
