name: what_to_eat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  geolocator: ^13.0.1
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
