import 'package:flutter/material.dart';

enum WhatToEatScreenState { categories, wheelOfFortune, foodSelected }

class FoodCategory {
  final String name;
  final List<String> foodItems;
  const FoodCategory({
    required this.name,
    required this.foodItems,
  });
}

class WhatToEatModel extends ChangeNotifier {
  WhatToEatScreenState _whatToEatScreenState = WhatToEatScreenState.categories;
  WhatToEatScreenState get whatToEatScreenState => _whatToEatScreenState;

  FoodCategory? _selectedCategory; // Store the selected category
  FoodCategory? get selectedCategory => _selectedCategory;

  void setWhatToEatScreenState(WhatToEatScreenState newState) {
    _whatToEatScreenState = newState;
    notifyListeners();
  }

  void setSelectedCategory(FoodCategory category) {
    _selectedCategory = category;
    notifyListeners();
  }

  static const List<FoodCategory> foodCategories = [
    FoodCategory(name: 'Comfort Foods', foodItems: [
      'Mac and Cheese',
      'Mashed Potatoes and Gravy',
      'Meatloaf',
      'Chicken Pot Pie',
      'Shepherd\'s Pie',
      'Beef Stew',
      'Chicken and Dumplings',
      'Grilled Cheese Sandwich',
      'Tomato Soup',
      'Sloppy Joes',
      'Baked Ziti',
      'Tuna Casserole',
      'Fettuccine Alfredo',
    ]),
    FoodCategory(name: 'Vegetarian and Vegan Dishes', foodItems: [
      'Vegan Buddha Bowl',
      'Grilled Vegetable Skewers',
      'Stuffed Bell Peppers',
      'Vegan Chili',
      'Lentil Soup',
      'Eggplant Parmesan',
      'Vegan Tacos',
      'Black Bean Burgers',
      'Vegan Lasagna',
      'Quinoa Salad',
      'Vegetable Stir Fry',
      'Falafel Wraps',
      'Tofu Scramble',
      'Sweet Potato and Black Bean Enchiladas',
    ]),
    FoodCategory(name: 'Breakfast & Brunch', foodItems: [
      'Pancakes',
      'French Toast',
      'Scrambled Eggs and Bacon',
      'Eggs Benedict',
      'Smoothie Bowl',
      'Avocado Toast',
      'Omelette',
      'Breakfast Burrito',
      'Belgian Waffles',
      'Granola and Yogurt',
      'Frittata',
      'Bagels with Cream Cheese',
      'Shakshuka',
      'Chia Pudding',
      'Overnight Oats',
    ]),
    FoodCategory(name: 'Pasta Varieties', foodItems: [
      'Spaghetti Bolognese',
      'Fettuccine Alfredo',
      'Penne Arrabbiata',
      'Carbonara',
      'Lasagna',
      'Ravioli',
      'Pesto Pasta',
      'Mac and Cheese',
      'Gnocchi',
      'Tortellini',
      'Ziti with Marinara',
      'Cacio e Pepe',
    ]),
    FoodCategory(name: 'Grilling and BBQ', foodItems: [
      'BBQ Ribs',
      'Grilled Steak',
      'Pulled Pork Sandwiches',
      'Grilled Corn on the Cob',
      'BBQ Chicken Wings',
      'Bratwurst',
      'Grilled Salmon',
      'Grilled Shrimp Skewers',
      'Grilled Portobello Mushrooms',
      'BBQ Brisket',
      'Smoky BBQ Beans',
      'Grilled Pineapple',
      'BBQ Pork Chops',
      'BBQ Baked Potatoes',
    ]),
    FoodCategory(name: 'Light and Healthy', foodItems: [
      'Grilled Salmon with Asparagus',
      'Quinoa and Black Bean Salad',
      'Zucchini Noodles with Marinara',
      'Turkey Lettuce Wraps',
      'Grilled Chicken Caesar Salad',
      'Greek Yogurt Parfait',
      'Spinach and Feta Stuffed Chicken Breast',
      'Avocado and Chickpea Salad',
      'Cauliflower Rice Stir Fry',
      'Broiled Cod with Lemon',
      'Roasted Brussels Sprouts and Sweet Potatoes',
      'Chia Seed Pudding',
      'Kale Smoothie',
      'Soba Noodle Salad',
    ]),
    FoodCategory(name: 'Low-Carb Meals', foodItems: [
      'Zucchini Noodles with Marinara',
      'Grilled Chicken with Avocado',
      'Cauliflower Rice Stir Fry',
      'Steak and Veggie Skewers',
      'Eggplant Lasagna',
      'Salmon with Asparagus',
      'Lettuce Wrap Tacos',
      'Keto Pizza',
      'Shrimp Scampi (zoodles)',
      'Cauliflower Crust Pizza',
      'Greek Salad with Chicken',
      'Stuffed Bell Peppers',
    ]),
    FoodCategory(name: 'Desserts', foodItems: [
      'Tiramisu',
      'Chocolate Cake',
      'Mochi Ice Cream',
      'Cheesecake',
      'Apple Pie',
      'Brownies',
      'Lemon Bars',
      'Panna Cotta',
      'Baklava',
      'Creme Brulee',
      'Churros',
      'Eclairs',
      'Fruit Tart',
      'Banoffee Pie',
      'Pavlova',
    ]),
    FoodCategory(name: 'Sides', foodItems: [
      'French Fries',
      'Garlic Bread',
      'Mashed Potatoes',
      'Coleslaw',
      'Steamed Broccoli',
      'Roasted Vegetables',
      'Caesar Salad',
      'Baked Beans',
      'Macaroni Salad',
      'Cornbread',
      'Grilled Asparagus',
      'Rice Pilaf',
      'Sweet Potato Fries',
      'Brussels Sprouts',
      'Potato Wedges',
      'Onion Rings',
      'Cucumber Salad',
    ]),
    FoodCategory(name: 'National Cuisines', foodItems: [
      'Mexico',
      'Italy',
      'Japan',
      'India',
      'China',
      'France',
      'Thailand',
      'Greece',
      'Finland',
      'Lebanon',
      'Spain',
      'Korea',
      'Vietnam',
      'Germany',
      'Morocco',
      'Turkey',
      'Brazil',
    ]),
    FoodCategory(name: 'Asian-Inspired Dishes', foodItems: [
      'Sushi Rolls',
      'Pad Thai',
      'General Tso\'s Chicken',
      'Ramen Noodle Soup',
      'Spring Rolls',
      'Kung Pao Chicken',
      'Korean Bibimbap',
      'Sweet and Sour Pork',
      'Dim Sum',
      'Teriyaki Chicken',
      'Miso Soup',
      'Thai Green Curry',
      'Chicken Satay',
      'Pho (Vietnamese Noodle Soup)',
      'Szechuan Beef',
      'Japanese Gyoza',
    ]),
    FoodCategory(name: 'Mediterranean Cuisine', foodItems: [
      'Greek Salad',
      'Hummus and Pita',
      'Tzatziki with Grilled Chicken',
      'Falafel',
      'Spanakopita',
      'Shawarma',
      'Baba Ganoush',
      'Grilled Lamb Chops',
      'Tabouleh',
      'Chicken Souvlaki',
      'Dolmas (Stuffed Grape Leaves)',
      'Fattoush Salad',
      'Moussaka',
      'Baklava',
      'Shakshuka',
      'Roasted Red Pepper Hummus',
    ]),
    FoodCategory(name: 'Mexican Cuisine', foodItems: [
      'Tacos',
      'Burritos',
      'Enchiladas',
      'Chiles Rellenos',
      'Guacamole',
      'Quesadillas',
      'Tamales',
      'Pozole',
      'Fajitas',
      'Sopa de Tortilla',
      'Churros',
      'Elote (Mexican Street Corn)',
      'Flan',
      'Huevos Rancheros',
    ]),
    FoodCategory(name: 'Italian Cuisine', foodItems: [
      'Lasagna',
      'Spaghetti Carbonara',
      'Risotto',
      'Margherita Pizza',
      'Ravioli',
      'Fettuccine Alfredo',
      'Pesto Pasta',
      'Minestrone Soup',
      'Caprese Salad',
      'Bruschetta',
      'Tiramisu',
      'Cannoli',
      'Gelato',
      'Spaghetti Bolognese',
      'Lasagna',
      'Margherita Pizza',
      'Fettuccine Alfredo',
      'Risotto',
      'Chicken Parmesan',
      'Caprese Salad',
      'Gnocchi with Pesto',
      'Eggplant Parmesan',
      'Stuffed Shells',
      'Minestrone Soup',
      'Antipasto Platter',
      'Tiramisu',
      'Cannoli',
      'Bruschetta',
    ]),
    FoodCategory(name: 'Japanese Cuisine', foodItems: [
      'Sushi',
      'Ramen',
      'Tempura',
      'Okonomiyaki',
      'Tonkatsu',
      'Udon',
      'Soba Noodles',
      'Miso Soup',
      'Takoyaki',
      'Gyoza',
      'Matcha Ice Cream',
      'Dorayaki',
      'Mochi',
    ]),
    FoodCategory(name: 'Indian Cuisine', foodItems: [
      'Butter Chicken',
      'Paneer Tikka',
      'Biryani',
      'Tandoori Chicken',
      'Samosas',
      'Palak Paneer',
      'Chole (Chickpea Curry)',
      'Rogan Josh',
      'Naan Bread',
      'Dosa',
      'Gulab Jamun',
      'Rasgulla',
      'Masala Chai',
      'Mango Lassi',
    ]),
    FoodCategory(name: 'Chinese Cuisine', foodItems: [
      'Sweet and Sour Pork',
      'Kung Pao Chicken',
      'Peking Duck',
      'Dumplings',
      'Spring Rolls',
      'Chow Mein',
      'Hot and Sour Soup',
      'Mapo Tofu',
      'Fried Rice',
      'Char Siu (BBQ Pork)',
      'Sesame Chicken',
      'Wonton Soup',
      'Mooncakes',
    ]),
    FoodCategory(name: 'French Cuisine', foodItems: [
      'Coq au Vin',
      'Bouillabaisse',
      'Ratatouille',
      'Quiche Lorraine',
      'Croque Monsieur',
      'Beef Bourguignon',
      'Escargots',
      'French Onion Soup',
      'Crepes',
      'Baguette with Cheese',
      'Madeleines',
      'Macarons',
      'Crème Brûlée',
      'Tarte Tatin',
    ]),
    FoodCategory(name: 'Fast Food Favorites', foodItems: [
      'Cheeseburgers',
      'Chicken Nuggets',
      'French Fries',
      'Hot Dogs',
      'Chicken Sandwich',
      'Fish and Chips',
      'Pizza',
      'Onion Rings',
      'Mozzarella Sticks',
      'Milkshakes',
      'Soft Tacos',
      'Sub Sandwiches',
    ]),
    FoodCategory(name: 'Holiday Specials', foodItems: [
      'Roast Turkey (Thanksgiving)',
      'Cranberry Sauce',
      'Pumpkin Pie',
      'Christmas Ham',
      'Stuffing',
      'Gingerbread Cookies',
      'Eggnog',
      'Latkes (Hanukkah)',
      'Yule Log Cake',
      'Roast Goose',
      'Easter Lamb',
      'Hot Cross Buns',
    ]),
    FoodCategory(name: 'Street Food', foodItems: [
      'Tacos al Pastor',
      'Shawarma Wraps',
      'Korean BBQ Skewers',
      'Falafel Sandwich',
      'Empanadas',
      'Churros',
      'Bao Buns',
      'Hot Dogs (NY-style)',
      'Corn Dogs',
      'Fish Tacos',
      'Poutine',
      'Pretzels',
      'Crepes',
    ]),
    FoodCategory(name: 'Comfort Desserts', foodItems: [
      'Chocolate Chip Cookies',
      'Brownies',
      'Apple Pie',
      'Banana Bread',
      'Ice Cream Sundae',
      'Chocolate Pudding',
      'Fudge',
      'Peach Cobbler',
      'Lemon Meringue Pie',
      'Cinnamon Rolls',
      'Rice Pudding',
      'Sticky Toffee Pudding',
    ]),
    FoodCategory(name: 'Soup and Stew Classics', foodItems: [
      'Chicken Noodle Soup',
      'Clam Chowder',
      'Minestrone',
      'French Onion Soup',
      'Beef Stew',
      'Cream of Mushroom Soup',
      'Split Pea Soup',
      'Gumbo',
      'Borscht',
      'Pho',
      'Lobster Bisque',
      'Lentil Soup',
      'Corn Chowder',
    ]),
    FoodCategory(name: 'Hearty Sandwiches', foodItems: [
      'Reuben',
      'Philly Cheesesteak',
      'Club Sandwich',
      'BLT',
      'Grilled Cheese',
      'Turkey Avocado Sandwich',
      'Pulled Pork Sandwich',
      'Cuban Sandwich',
      'Pastrami on Rye',
      'Italian Sub',
      'French Dip',
      'Chicken Salad Sandwich',
    ]),
    FoodCategory(name: 'Smoothies and Shakes', foodItems: [
      'Strawberry Banana Smoothie',
      'Mango Lassi',
      'Green Detox Smoothie',
      'Peanut Butter Protein Shake',
      'Chocolate Milkshake',
      'Tropical Smoothie',
      'Blueberry Spinach Smoothie',
      'Avocado Smoothie',
      'Vanilla Protein Shake',
      'Iced Coffee Smoothie',
      'Raspberry Coconut Shake',
      'Matcha Smoothie',
    ]),
  ];
}
